server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
        - id: goods-service
          uri: http://localhost:8082
          predicates:
            - Path=/goods/**
        - id: goods-service-admin
          uri: http://localhost:8082
          predicates:
            - Path=/admin/**
